from __future__ import annotations

from collections.abc import Awaitable, Callable
from time import perf_counter
from typing import Any

from ..retrieval import ProductSourceAdapter
from ..types import Product, RetrievalBatch
from .errors import AgentHarnessError
from .sql import ProductSQLStore

type ProgressCallback = Callable[[str], Awaitable[None] | None]
type EmitProgressCallback = Callable[[ProgressCallback | None, str], Awaitable[None]]


def build_retrieval_tool_specs() -> list[dict[str, Any]]:
    return [
        {
            "type": "function",
            "function": {
                "name": "ask_clarification",
                "description": (
                    "Ask the user a popup clarification question with 3 to 5 "
                    "choices and an optional preference dimension."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "question": {
                            "type": "string",
                            "description": "The user-facing clarification question.",
                        },
                        "suggested_choices": {
                            "type": "array",
                            "description": "Three to five suggested options for the popup.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {"type": "string"},
                                    "label": {"type": "string"},
                                    "description": {"type": "string"},
                                },
                                "required": ["id", "label", "description"],
                                "additionalProperties": False,
                            },
                            "minItems": 3,
                            "maxItems": 5,
                        },
                        "preference_dimension": {
                            "type": "string",
                            "description": (
                                "Optional metadata name for the preference being resolved."
                            ),
                        },
                    },
                    "required": ["question", "suggested_choices"],
                    "additionalProperties": False,
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_amazon",
                "description": (
                    "Search Amazon with one query string and return up to 50 "
                    "normalized product results."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The Amazon search query generated by the agent.",
                        }
                    },
                    "required": ["query"],
                    "additionalProperties": False,
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_ebay",
                "description": (
                    "Search eBay with one query string and return up to 50 "
                    "normalized product results."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The eBay search query generated by the agent.",
                        }
                    },
                    "required": ["query"],
                    "additionalProperties": False,
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_newegg",
                "description": (
                    "Search Newegg with one query string and return up to 50 "
                    "normalized product results."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The Newegg search query generated by the agent.",
                        }
                    },
                    "required": ["query"],
                    "additionalProperties": False,
                },
            },
        },
    ]


def build_ranking_sql_tool_specs() -> list[dict[str, Any]]:
    return [
        {
            "type": "function",
            "function": {
                "name": "query_product_store",
                "description": (
                    "Run a read-only SQL query against the in-memory normalized product store."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "sql": {
                            "type": "string",
                            "description": "A read-only SELECT query over the `products` table.",
                        }
                    },
                    "required": ["sql"],
                    "additionalProperties": False,
                },
            },
        }
    ]


async def handle_search_amazon(
    *,
    arguments: dict[str, Any],
    adapter: ProductSourceAdapter,
    emit_progress: EmitProgressCallback,
    progress: ProgressCallback | None,
    retrieved_products: dict[str, Product],
    retrieval_batches: list[RetrievalBatch],
) -> dict[str, Any]:
    query = str(arguments.get("query", "")).strip()
    if not query:
        raise AgentHarnessError("search_amazon requires a non-empty query.")

    return await run_search_tool(
        adapter=adapter,
        query=query,
        tool_name="search_amazon",
        emit_progress=emit_progress,
        progress=progress,
        retrieved_products=retrieved_products,
        retrieval_batches=retrieval_batches,
    )


async def handle_search_ebay(
    *,
    arguments: dict[str, Any],
    adapter: ProductSourceAdapter,
    emit_progress: EmitProgressCallback,
    progress: ProgressCallback | None,
    retrieved_products: dict[str, Product],
    retrieval_batches: list[RetrievalBatch],
) -> dict[str, Any]:
    query = str(arguments.get("query", "")).strip()
    if not query:
        raise AgentHarnessError("search_ebay requires a non-empty query.")

    return await run_search_tool(
        adapter=adapter,
        query=query,
        tool_name="search_ebay",
        emit_progress=emit_progress,
        progress=progress,
        retrieved_products=retrieved_products,
        retrieval_batches=retrieval_batches,
    )


async def handle_search_newegg(
    *,
    arguments: dict[str, Any],
    adapter: ProductSourceAdapter,
    emit_progress: EmitProgressCallback,
    progress: ProgressCallback | None,
    retrieved_products: dict[str, Product],
    retrieval_batches: list[RetrievalBatch],
) -> dict[str, Any]:
    query = str(arguments.get("query", "")).strip()
    if not query:
        raise AgentHarnessError("search_newegg requires a non-empty query.")

    return await run_search_tool(
        adapter=adapter,
        query=query,
        tool_name="search_newegg",
        emit_progress=emit_progress,
        progress=progress,
        retrieved_products=retrieved_products,
        retrieval_batches=retrieval_batches,
    )


async def run_search_tool(
    *,
    adapter: ProductSourceAdapter,
    query: str,
    tool_name: str,
    emit_progress: EmitProgressCallback,
    progress: ProgressCallback | None,
    retrieved_products: dict[str, Product],
    retrieval_batches: list[RetrievalBatch],
) -> dict[str, Any]:
    await emit_progress(
        progress,
        f"[plan] Search {adapter.source_name} for: {query}",
    )
    started = perf_counter()
    products = await adapter.search(query, limit=50)
    latency_ms = int((perf_counter() - started) * 1000)
    retrieval_batches.append(
        RetrievalBatch(
            source=adapter.source_name,
            products=products,
            latency_ms=latency_ms,
        )
    )
    for product in products:
        retrieved_products[product.product_url] = product
    await emit_progress(
        progress,
        f"[action] {tool_name} returned {len(products)} product(s) in {latency_ms} ms.",
    )
    status = "usable" if len(products) >= 3 else "too_few_results"
    return {
        "query": query,
        "source": adapter.source_name,
        "result_count": len(products),
        "status": status,
        "message": (
            f"{adapter.source_name} search for '{query}' returned {len(products)} product(s) "
            f"in {latency_ms} ms."
        ),
    }


def run_product_store_query(
    *,
    arguments: dict[str, Any],
    store: ProductSQLStore,
) -> dict[str, Any]:
    sql = str(arguments.get("sql", "")).strip()
    if not sql:
        raise AgentHarnessError("query_product_store requires a non-empty sql string.")
    return store.query(sql)


def build_tool_specs() -> list[dict[str, Any]]:
    return build_retrieval_tool_specs()
